FROM ubuntu:16.04
MAINTAINER PixelPerfect <pixelperfectpon3@gmail.com>

WORKDIR /opt/

# Installing Dependencies
RUN apt update -y
RUN apt upgrade -y
RUN apt dist-upgrade -y
RUN apt-get install software-properties-common apt-transport-https -y
RUN add-apt-repository ppa:jonathonf/ffmpeg-3 -y
RUN add-apt-repository ppa:nilarimogard/webupd8 -y
RUN sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list'
RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 417A0893
RUN apt update -y
RUN apt upgrade -y
RUN apt dist-upgrade -y
RUN apt install git -y
RUN apt install dotnet-dev-1.0.4 libopus0 opus-tools libopus-dev libsodium-dev ffmpeg tmux sudo youtube-dl dotnet-sharedframework-microsoft.netcore.app-1.1.2  -y

#Download and install stable version of Nadeko
RUN curl -L https://raw.githubusercontent.com/iPonyRadio/nadeko/1.5/nadeko_installer_1_4.sh | sh \
	&& curl -L https://raw.githubusercontent.com/iPonyRadio/nadeko/1.5/nadeko_autorestart.sh > nadeko.sh \
	&& chmod 755 nadeko.sh

VOLUME ["/root/nadeko"]

CMD ["/opt/nadeko.sh"]
