FROM microsoft/dotnet:2.0.0-preview2-sdk-stretch
MAINTAINER PixelPerfect <pixelperfectpon3@gmail.com>

WORKDIR /opt/

#Install required software
RUN echo "deb http://www.deb-multimedia.org stable main non-free" | tee /etc/apt/sources.list.d/debian-backports.list \
	&& apt-get update \
	&& apt-get install -y --force-yes deb-multimedia-keyring \
	&& apt-get update \
	&& apt-get install -y git libopus0 opus-tools libopus-dev libsodium-dev ffmpeg

#Download and install stable version of Nadeko
RUN curl -L https://raw.githubusercontent.com/iPonyRadio/nadeko/1.4/nadeko_installer_1_4.sh | sh \
	&& curl -L https://raw.githubusercontent.com/iPonyRadio/nadeko/1.4/nadeko_autorestart.sh > nadeko.sh \
	&& chmod 755 nadeko.sh

VOLUME ["/root/nadeko"]

CMD ["/opt/nadeko.sh"]
